name: java-app
run-name: Java-app workflow
on:
  push:
    paths:
      - 'java-app/**'
      - '.github/workflows/java-app.yml'
jobs:
  building-java-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: java-app Test run
        run: | 
          date
          ls -la
          pwd 
          echo "TEST---------------------------------"
          env
      - run: mvn -version 
      - run: java -version