name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      - name: Test run
        run: | 
          date
          ls -la
          pwd 
          echo "TEST---------------------------------"
          env
      - run: npm install --global surge
      - run: surge --version
      - run: date >> README.md
      - run: npm install
        working-directory: ./web-frontend/test/
      - run: npm run build
        working-directory: ./web-frontend/test/
      - name: Surge deploy
        env:
          super_secret: ${{ secrets.MIO_SURGE_TOKEN }}
        working-directory: ./web-frontend/test/
        run: | 
          echo "questo è il super_secret ${super_secret}"
          export SURGE_TOKEN=$super_secret
          surge ./build/ jumbled-motion.surge.sh
      - run: echo "Fine"