name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  action-environment-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      - run: npm install --global surge
      - run: surge --version
      - run: date >> README.md
      - name: Surge deploy
        run: | 
          export SURGE_TOKEN=c0f11c24344e5acb2495ff9901c8a791
          surge . jumbled-motion.surge.sh
      - name: Test run
        run: | 
          date
          ls -la
          pwd 
          echo "CIAO---------------------------------"
          env
      - run: echo "Fineeeeeeeeeeeeeeeeeeeeeeeeeeee"